on: push
name: Build and Test
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'
      - name: Install
        run: yarn install
      - name: Test
        run: yarn test
      - name: Build
        run: yarn build
